I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 708, in script
    show chabs_sitting at cebter, with dissolve
  File "game/script.rpy", line 708, in <module>
    show chabs_sitting at cebter, with dissolve
NameError: name 'cebter' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 708, in script
    show chabs_sitting at cebter, with dissolve
  File "/Applications/renpy-8.3.2-sdk/renpy/ast.py", line 1124, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Applications/renpy-8.3.2-sdk/renpy/ast.py", line 1083, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/Applications/renpy-8.3.2-sdk/renpy/ast.py", line 1083, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "/Applications/renpy-8.3.2-sdk/renpy/python.py", line 1215, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "/Applications/renpy-8.3.2-sdk/renpy/python.py", line 1208, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 708, in <module>
    show chabs_sitting at cebter, with dissolve
NameError: name 'cebter' is not defined

macOS-15.3.2-arm64-arm-64bit arm64
Ren'Py 8.3.6.25022803
kinaiyagame_3.0 1.0
Wed Mar 26 13:38:55 2025
